<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bookingdetail/_create.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:00:46 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create BookingDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('bookingdetails.index')}}">Manage</a>
<form action="{{route('bookingdetails.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="booking_id" class="col-sm-2 col-form-label">Booking</label>
	<div class="col-sm-10">
		<select class="form-control" name="booking_id" id="booking_id">
			@foreach($bookings as $booking)
				<option value="{{$booking->id}}">{{$booking->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="service_id" class="col-sm-2 col-form-label">Service</label>
	<div class="col-sm-10">
		<select class="form-control" name="service_id" id="service_id">
			@foreach($services as $service)
				<option value="{{$service->id}}">{{$service->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="additional_service_id" class="col-sm-2 col-form-label">Additional_Service</label>
	<div class="col-sm-10">
		<select class="form-control" name="additional_service_id" id="additional_service_id">
			@foreach($additional_services as $additional_service)
				<option value="{{$additional_service->id}}">{{$additional_service->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="booking_notes" class="col-sm-2 col-form-label">Booking Notes</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="booking_notes" id="booking_notes" placeholder="Booking Notes"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" id="price" placeholder="Price">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
