<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bookingdetail/_edit.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:00:46 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit BookingDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('bookingdetails.index')}}">Manage</a>
<form action="{{route('bookingdetails.update',$bookingdetail)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="booking_id" class="col-sm-2 col-form-label">Booking</label>
	<div class="col-sm-10">
		<select class="form-control" name="booking_id" id="booking_id">
			@foreach($bookings as $booking)
				@if($booking->id==$bookingdetail->booking_id)
					<option value="{{$booking->id}}" selected>{{$booking->name}}</option>
				@else
					<option value="{{$booking->id}}">{{$booking->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="service_id" class="col-sm-2 col-form-label">Service</label>
	<div class="col-sm-10">
		<select class="form-control" name="service_id" id="service_id">
			@foreach($services as $service)
				@if($service->id==$bookingdetail->service_id)
					<option value="{{$service->id}}" selected>{{$service->name}}</option>
				@else
					<option value="{{$service->id}}">{{$service->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="additional_service_id" class="col-sm-2 col-form-label">Additional_Service</label>
	<div class="col-sm-10">
		<select class="form-control" name="additional_service_id" id="additional_service_id">
			@foreach($additional_services as $additional_service)
				@if($additional_service->id==$bookingdetail->additional_service_id)
					<option value="{{$additional_service->id}}" selected>{{$additional_service->name}}</option>
				@else
					<option value="{{$additional_service->id}}">{{$additional_service->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" value="{{$bookingdetail->quantity}}" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="booking_notes" class="col-sm-2 col-form-label">Booking Notes</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="booking_notes" value="{{$bookingdetail->booking_notes}}" id="booking_notes" placeholder="Booking Notes">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$bookingdetail->price}}" id="price" placeholder="Price">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
