<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bookingdetail/_index.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:00:46 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage BookingDetail')
@section('style')


@endsection
@section('page')
<a href="{{route('bookingdetails.create')}}">New BookingDetail</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Booking Id</th>
			<th>Service Id</th>
			<th>Additional Service Id</th>
			<th>Quantity</th>
			<th>Booking Notes</th>
			<th>Price</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($bookingdetails as $bookingdetail)
		<tr>
			<td>{{$bookingdetail->id}}</td>
			<td>{{$bookingdetail->booking_id}}</td>
			<td>{{$bookingdetail->service_id}}</td>
			<td>{{$bookingdetail->additional_service_id}}</td>
			<td>{{$bookingdetail->quantity}}</td>
			<td>{{$bookingdetail->booking_notes}}</td>
			<td>{{$bookingdetail->price}}</td>
			<td>{{$bookingdetail->created_at}}</td>
			<td>{{$bookingdetail->updated_at}}</td>

			<td>
			<form action = "{{route('bookingdetails.destroy',$bookingdetail->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('bookingdetails.show',$bookingdetail->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('bookingdetails.edit',$bookingdetail->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
