<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/bookingdetail/_show.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:00:46 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show BookingDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('bookingdetails.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$bookingdetail->id}}</td></tr>
		<tr><th>Booking Id</th><td>{{$bookingdetail->booking_id}}</td></tr>
		<tr><th>Service Id</th><td>{{$bookingdetail->service_id}}</td></tr>
		<tr><th>Additional Service Id</th><td>{{$bookingdetail->additional_service_id}}</td></tr>
		<tr><th>Quantity</th><td>{{$bookingdetail->quantity}}</td></tr>
		<tr><th>Booking Notes</th><td>{{$bookingdetail->booking_notes}}</td></tr>
		<tr><th>Price</th><td>{{$bookingdetail->price}}</td></tr>
		<tr><th>Created At</th><td>{{$bookingdetail->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$bookingdetail->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
