<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/additionalservice/_index.blade.php" was generated by ProBot AI.
* Date: 2/27/2025 9:56:42 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage AdditionalService')
@section('style')


@endsection
@section('page')
<a href="{{route('additionalservices.create')}}">New AdditionalService</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($additionalservices as $additionalservice)
		<tr>

			<td>
			<form action = "{{route('additionalservices.destroy',$additionalservice->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('additionalservices.show',$additionalservice->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('additionalservices.edit',$additionalservice->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
