<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/additionalservice/_show.blade.php" was generated by ProBot AI.
* Date: 2/27/2025 9:56:42 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show AdditionalService')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('additionalservices.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>

</tbody>
</table>
@endsection
@section('script')


@endsection
