<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/subcategory/_edit.blade.php" was generated by ProBot AI.
* Date: 2/23/2025 10:56:52 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit SubCategory')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('subcategorys.index')}}">Manage</a>
<form action="{{route('subcategorys.update',$subcategory)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="id" class="col-sm-2 col-form-label">Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="id" value="{{$subcategory->id}}" id="id" placeholder="Id">
	</div>
</div>
<div class="row mb-3">
	<label for="category_id" class="col-sm-2 col-form-label">Category Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="category_id" value="{{$subcategory->category_id}}" id="category_id" placeholder="Category Id">
	</div>
</div>
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$subcategory->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="description" value="{{$subcategory->description}}" id="description" placeholder="Description">
	</div>
</div>
<div class="row mb-3">
	<label for="image_url" class="col-sm-2 col-form-label">Image Url</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="image_url" value="{{$subcategory->image_url}}" id="image_url" placeholder="Image Url">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
