<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/subcategory/_index.blade.php" was generated by ProBot AI.
* Date: 2/23/2025 10:56:52 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage SubCategory')
@section('style')


@endsection
@section('page')
<a href="{{route('subcategorys.create')}}">New SubCategory</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Category Id</th>
			<th>Name</th>
			<th>Description</th>
			<th>Image Url</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($subcategorys as $subcategory)
		<tr>
			<td>{{$subcategory->id}}</td>
			<td>{{$subcategory->category_id}}</td>
			<td>{{$subcategory->name}}</td>
			<td>{{$subcategory->description}}</td>
			<td>{{$subcategory->image_url}}</td>

			<td>
			<form action = "{{route('subcategorys.destroy',$subcategory->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('subcategorys.show',$subcategory->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('subcategorys.edit',$subcategory->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
