<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/booking/_edit.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:34:27 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Booking')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('bookings.index')}}">Manage</a>
<form action="{{route('bookings.update',$booking)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="id" class="col-sm-2 col-form-label">Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="id" value="{{$booking->id}}" id="id" placeholder="Id">
	</div>
</div>
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="customer_id" value="{{$booking->customer_id}}" id="customer_id" placeholder="Customer Id">
	</div>
</div>
<div class="row mb-3">
	<label for="provider_id" class="col-sm-2 col-form-label">Provider Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="provider_id" value="{{$booking->provider_id}}" id="provider_id" placeholder="Provider Id">
	</div>
</div>
<div class="row mb-3">
	<label for="service_id" class="col-sm-2 col-form-label">Service Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="service_id" value="{{$booking->service_id}}" id="service_id" placeholder="Service Id">
	</div>
</div>
<div class="row mb-3">
	<label for="status_id" class="col-sm-2 col-form-label">Status Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="status_id" value="{{$booking->status_id}}" id="status_id" placeholder="Status Id">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$booking->price}}" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="payment_status_id" class="col-sm-2 col-form-label">Payment Status Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="payment_status_id" value="{{$booking->payment_status_id}}" id="payment_status_id" placeholder="Payment Status Id">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
