<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/booking/_index.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:34:27 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Booking')
@section('style')


@endsection
@section('page')
<a href="{{route('bookings.create')}}">New Booking</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Customer Id</th>
			<th>Provider Id</th>
			<th>Service Id</th>
			<th>Status Id</th>
			<th>Scheduled Time</th>
			<th>Price</th>
			<th>Payment Status Id</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($bookings as $booking)
		<tr>
			<td>{{$booking->id}}</td>
			<td>{{$booking->customer_id}}</td>
			<td>{{$booking->provider_id}}</td>
			<td>{{$booking->service_id}}</td>
			<td>{{$booking->status_id}}</td>
			<td>{{$booking->scheduled_time}}</td>
			<td>{{$booking->price}}</td>
			<td>{{$booking->payment_status_id}}</td>
			<td>{{$booking->created_at}}</td>
			<td>{{$booking->updated_at}}</td>

			<td>
			<form action = "{{route('bookings.destroy',$booking->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('bookings.show',$booking->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('bookings.edit',$booking->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
