<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/category/_index.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 11:52:26 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Category')
@section('style')


@endsection
@section('page')
<a href="{{route('categorys.create')}}">New Category</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Description</th>
			<th>Image Url</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($categorys as $category)
		<tr>
			<td>{{$category->id}}</td>
			<td>{{$category->name}}</td>
			<td>{{$category->description}}</td>
			<td>{{$category->image_url}}</td>

			<td>
			<form action = "{{route('categorys.destroy',$category->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('categorys.show',$category->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('categorys.edit',$category->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
