<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/category/_show.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 11:52:26 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Category')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('categorys.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$category->id}}</td></tr>
		<tr><th>Name</th><td>{{$category->name}}</td></tr>
		<tr><th>Description</th><td>{{$category->description}}</td></tr>
		<tr><th>Image Url</th><td>{{$category->image_url}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
