<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/provider/_edit.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 11:52:47 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Provider')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('providers.index')}}">Manage</a>
<form action="{{route('providers.update',$provider)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="id" class="col-sm-2 col-form-label">Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="id" value="{{$provider->id}}" id="id" placeholder="Id">
	</div>
</div>
<div class="row mb-3">
	<label for="user_id" class="col-sm-2 col-form-label">User Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="user_id" value="{{$provider->user_id}}" id="user_id" placeholder="User Id">
	</div>
</div>
<div class="row mb-3">
	<label for="business_name" class="col-sm-2 col-form-label">Business Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="business_name" value="{{$provider->business_name}}" id="business_name" placeholder="Business Name">
	</div>
</div>
<div class="row mb-3">
	<label for="business_description" class="col-sm-2 col-form-label">Business Description</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="business_description" value="{{$provider->business_description}}" id="business_description" placeholder="Business Description">
	</div>
</div>
<div class="row mb-3">
	<label for="address" class="col-sm-2 col-form-label">Address</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="address" value="{{$provider->address}}" id="address" placeholder="Address">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
