<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/provider/_index.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 11:52:47 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Provider')
@section('style')


@endsection
@section('page')
<a href="{{route('providers.create')}}">New Provider</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>User Id</th>
			<th>Business Name</th>
			<th>Business Description</th>
			<th>Address</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($providers as $provider)
		<tr>
			<td>{{$provider->id}}</td>
			<td>{{$provider->user_id}}</td>
			<td>{{$provider->business_name}}</td>
			<td>{{$provider->business_description}}</td>
			<td>{{$provider->address}}</td>
			<td>{{$provider->created_at}}</td>
			<td>{{$provider->updated_at}}</td>

			<td>
			<form action = "{{route('providers.destroy',$provider->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('providers.show',$provider->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('providers.edit',$provider->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
