<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/provider/_show.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 11:52:47 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Provider')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('providers.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$provider->id}}</td></tr>
		<tr><th>User Id</th><td>{{$provider->user_id}}</td></tr>
		<tr><th>Business Name</th><td>{{$provider->business_name}}</td></tr>
		<tr><th>Business Description</th><td>{{$provider->business_description}}</td></tr>
		<tr><th>Address</th><td>{{$provider->address}}</td></tr>
		<tr><th>Created At</th><td>{{$provider->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$provider->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
