<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customer/_edit.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 11:51:55 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Customer')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('customers.index')}}">Manage</a>
<form action="{{route('customers.update',$customer)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="id" class="col-sm-2 col-form-label">Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="id" value="{{$customer->id}}" id="id" placeholder="Id">
	</div>
</div>
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$customer->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="email" class="col-sm-2 col-form-label">Email</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="email" value="{{$customer->email}}" id="email" placeholder="Email">
	</div>
</div>
<div class="row mb-3">
	<label for="phone_number" class="col-sm-2 col-form-label">Phone Number</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="phone_number" value="{{$customer->phone_number}}" id="phone_number" placeholder="Phone Number">
	</div>
</div>
<div class="row mb-3">
	<label for="password" class="col-sm-2 col-form-label">Password</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="password" value="{{$customer->password}}" id="password" placeholder="Password">
	</div>
</div>
<div class="row mb-3">
	<label for="address" class="col-sm-2 col-form-label">Address</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="address" value="{{$customer->address}}" id="address" placeholder="Address">
	</div>
</div>
<div class="row mb-3">
	<label for="profile_picture" class="col-sm-2 col-form-label">Profile Picture</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="profile_picture" value="{{$customer->profile_picture}}" id="profile_picture" placeholder="Profile Picture">
	</div>
</div>
<div class="row mb-3">
	<label for="location" class="col-sm-2 col-form-label">Location</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="location" value="{{$customer->location}}" id="location" placeholder="Location">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
