<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customer/_index.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:02:59 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Customer')
@section('style')


@endsection
@section('page')
<a href="{{route('customers.create')}}">New Customer</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Phone Number</th>
			<th>Password</th>
			<th>Street Address</th>
			<th>City</th>
			<th>State</th>
			<th>Postal Code</th>
			<th>Profile Picture</th>
			<th>Booking Notes</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($customers as $customer)
		<tr>
			<td>{{$customer->id}}</td>
			<td>{{$customer->first_name}}</td>
			<td>{{$customer->last_name}}</td>
			<td>{{$customer->email}}</td>
			<td>{{$customer->phone_number}}</td>
			<td>{{$customer->password}}</td>
			<td>{{$customer->street_address}}</td>
			<td>{{$customer->city}}</td>
			<td>{{$customer->state}}</td>
			<td>{{$customer->postal_code}}</td>
			<td>{{$customer->profile_picture}}</td>
			<td>{{$customer->booking_notes}}</td>
			<td>{{$customer->created_at}}</td>
			<td>{{$customer->updated_at}}</td>

			<td>
			<form action = "{{route('customers.destroy',$customer->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('customers.show',$customer->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('customers.edit',$customer->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
