<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customer/_show.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 10:02:59 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Customer')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('customers.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$customer->id}}</td></tr>
		<tr><th>First Name</th><td>{{$customer->first_name}}</td></tr>
		<tr><th>Last Name</th><td>{{$customer->last_name}}</td></tr>
		<tr><th>Email</th><td>{{$customer->email}}</td></tr>
		<tr><th>Phone Number</th><td>{{$customer->phone_number}}</td></tr>
		<tr><th>Password</th><td>{{$customer->password}}</td></tr>
		<tr><th>Street Address</th><td>{{$customer->street_address}}</td></tr>
		<tr><th>City</th><td>{{$customer->city}}</td></tr>
		<tr><th>State</th><td>{{$customer->state}}</td></tr>
		<tr><th>Postal Code</th><td>{{$customer->postal_code}}</td></tr>
		<tr><th>Profile Picture</th><td>{{$customer->profile_picture}}</td></tr>
		<tr><th>Booking Notes</th><td>{{$customer->booking_notes}}</td></tr>
		<tr><th>Created At</th><td>{{$customer->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$customer->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
