<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/review/_create.blade.php" was generated by ProBot AI.
* Date: 2/25/2025 12:45:48 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Review')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('reviews.index')}}">Manage</a>
<form action="{{route('reviews.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="service_id" class="col-sm-2 col-form-label">Service</label>
	<div class="col-sm-10">
		<select class="form-control" name="service_id" id="service_id">
			@foreach($services as $service)
				<option value="{{$service->id}}">{{$service->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				<option value="{{$customer->id}}">{{$customer->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="rating" class="col-sm-2 col-form-label">Rating</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="rating" id="rating" placeholder="Rating">
	</div>
</div>
<div class="row mb-3">
	<label for="review" class="col-sm-2 col-form-label">Review</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="review" id="review" placeholder="Review"></textarea>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
