<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PaymentMethodController.php" was generated by ProBot AI.
* Date: 3/10/2025 11:47:56 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PaymentMethod;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PaymentMethodController extends Controller{
	public function index(){
		$paymentmethods = PaymentMethod::paginate(10);
		return view("pages.erp.paymentmethod.index",["paymentmethods"=>$paymentmethods]);
	}
	public function create(){
		return view("pages.erp.paymentmethod.create",[]);
	}
	public function store(Request $request){
		//PaymentMethod::create($request->all());
		$paymentmethod = new PaymentMethod;
		$paymentmethod->id=$request->id;
		$paymentmethod->name=$request->name;

		$paymentmethod->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$paymentmethod = PaymentMethod::find($id);
		return view("pages.erp.paymentmethod.show",["paymentmethod"=>$paymentmethod]);
	}
	public function edit(PaymentMethod $paymentmethod){
		return view("pages.erp.paymentmethod.edit",["paymentmethod"=>$paymentmethod,]);
	}
	public function update(Request $request,PaymentMethod $paymentmethod){
		//PaymentMethod::update($request->all());
		$paymentmethod = PaymentMethod::find($paymentmethod->id);
		$paymentmethod->id=$request->id;
		$paymentmethod->name=$request->name;

		$paymentmethod->save();

		return redirect()->route("paymentmethods.index")->with('success','Updated Successfully.');
	}
	public function destroy(PaymentMethod $paymentmethod){
		$paymentmethod->delete();
		return redirect()->route("paymentmethods.index")->with('success', 'Deleted Successfully.');
	}
}
?>
