<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SubCategoryController.php" was generated by ProBot AI.
* Date: 2/23/2025 10:56:51 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\SubCategory;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SubCategoryController extends Controller{
	public function index(){
		$subcategorys = SubCategory::paginate(10);
		return view("pages.erp.subcategory.index",["subcategorys"=>$subcategorys]);
	}
	public function create(){
		return view("pages.erp.subcategory.create",[]);
	}
	public function store(Request $request){
		//SubCategory::create($request->all());
		$subcategory = new SubCategory;
		$subcategory->id=$request->id;
		$subcategory->category_id=$request->category_id;
		$subcategory->name=$request->name;
		$subcategory->description=$request->description;
		$subcategory->image_url=$request->image_url;

		$subcategory->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$subcategory = SubCategory::find($id);
		return view("pages.erp.subcategory.show",["subcategory"=>$subcategory]);
	}
	public function edit(SubCategory $subcategory){
		return view("pages.erp.subcategory.edit",["subcategory"=>$subcategory,]);
	}
	public function update(Request $request,SubCategory $subcategory){
		//SubCategory::update($request->all());
		$subcategory = SubCategory::find($subcategory->id);
		$subcategory->id=$request->id;
		$subcategory->category_id=$request->category_id;
		$subcategory->name=$request->name;
		$subcategory->description=$request->description;
		$subcategory->image_url=$request->image_url;

		$subcategory->save();

		return redirect()->route("subcategorys.index")->with('success','Updated Successfully.');
	}
	public function destroy(SubCategory $subcategory){
		$subcategory->delete();
		return redirect()->route("subcategorys.index")->with('success', 'Deleted Successfully.');
	}
}
?>
