<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Booking.php" was generated by ProBot AI.
* Date: 3/10/2025 10:34:27 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Booking extends Model{


}
?>
