<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PaymentMethod.php" was generated by ProBot AI.
* Date: 3/10/2025 11:47:57 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PaymentMethod extends Model{


}
?>
