<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Review.php" was generated by ProBot AI.
* Date: 2/25/2025 12:45:48 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Review extends Model{


}
?>
