<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_AdditionalService.php" was generated by ProBot AI.
* Date: 2/27/2025 9:56:42 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class AdditionalService extends Model{


}
?>
