<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_BookingDetail.php" was generated by ProBot AI.
* Date: 3/10/2025 10:00:46 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class BookingDetail extends Model{


 }
?>
