<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Customer.php" was generated by ProBot AI.
* Date: 2/22/2025 11:51:55 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Customer extends Model{


}
?>
