<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Service.php" was generated by ProBot AI.
* Date: 2/22/2025 1:11:49 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Service extends Model{


}
?>
