<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Service.php" was generated by ProBot AI.
* Date: 2/22/2025 1:11:49 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;

use App\Models\localservice\Review;
use Illuminate\Database\Eloquent\Model;
class Service extends Model{

    function category(){
        return $this->belongsTo(Category::class);
    }
    function provider(){
        return $this->belongsTo(Provider::class);
    }
    // function review(){
    //     return $this->hasOne(Review::class);
    // }

}
?>
