<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_SubCategory.php" was generated by ProBot AI.
* Date: 2/23/2025 10:56:52 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class SubCategory extends Model{


}
?>
