<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentmethod/_index.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 11:47:57 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PaymentMethod')
@section('style')


@endsection
@section('page')
<a href="{{route('paymentmethods.create')}}">New PaymentMethod</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($paymentmethods as $paymentmethod)
		<tr>
			<td>{{$paymentmethod->id}}</td>
			<td>{{$paymentmethod->name}}</td>

			<td>
			<form action = "{{route('paymentmethods.destroy',$paymentmethod->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('paymentmethods.show',$paymentmethod->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('paymentmethods.edit',$paymentmethod->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
