<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentmethod/_show.blade.php" was generated by ProBot AI.
* Date: 3/10/2025 11:47:57 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PaymentMethod')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('paymentmethods.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$paymentmethod->id}}</td></tr>
		<tr><th>Name</th><td>{{$paymentmethod->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
