<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/service/_show.blade.php" was generated by ProBot AI.
* Date: 2/22/2025 1:11:49 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Service')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('services.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$service->id}}</td></tr>
		<tr><th>Category Id</th><td>{{$service->category_id}}</td></tr>
		<tr><th>Provider Id</th><td>{{$service->provider_id}}</td></tr>
		<tr><th>Title</th><td>{{$service->title}}</td></tr>
		<tr><th>Description</th><td>{{$service->description}}</td></tr>
		<tr><th>Price</th><td>{{$service->price}}</td></tr>
		<tr><th>Status Id</th><td>{{$service->status_id}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
